services:
  blu-node:
    container_name: blu-node
    image: ghcr.io/blu-whale/blu-node:513c727
    restart: always
    environment:
      - CONFIG_FILE_PATH=/app/conf.yaml
    volumes:
      - ./conf/config.yaml:/app/conf.yaml
      - ./logs/:/app/logs/
    command: ["./main","-c", "/app/conf.yaml"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      - blu-node

networks:
  blu-node:
    driver: bridge
